'use client'

import { Share2, CheckCircle2, X, Edit3, Clock } from 'lucide-react'

const MOCK_POSTS = [
  {
    id: '1',
    platform: 'X',
    scheduledFor: 'Mar 12 · 10:00am',
    body: `He's building Neolog — an AI that listens to everything he records and turns raw brain dumps into structured intelligence. Today he's fixing the video pipeline that processes 4GB iPhone recordings without timing out on Vercel.`,
    source: 'Mar 9 morning log',
    status: 'pending',
  },
  {
    id: '2',
    platform: 'X',
    scheduledFor: 'Mar 13 · 9:00am',
    body: `The insight that changed how he thinks about building: you don't need to organize your ideas — you need a system that organizes them for you. That's the pivot behind Neolog.`,
    source: 'Mar 8 evening log',
    status: 'pending',
  },
]

export default function PostQueuePage() {
  return (
    <div className="max-w-4xl mx-auto px-6 py-8 md:py-12">
      <div className="mb-8">
        <h1 className="font-display text-3xl font-bold text-[var(--text-primary)]">Post Queue</h1>
        <p className="text-[var(--text-secondary)] mt-1">
          Posts generated by Neolog based on your logs. Review and approve before they go out.
        </p>
      </div>

      {/* Tabs */}
      <div className="flex gap-1 border-b border-[var(--border-medium)] mb-6">
        {['Ready (2)', 'Scheduled (0)', 'Posted (0)'].map((tab, i) => (
          <button
            key={tab}
            className={`px-4 py-2.5 text-sm font-medium transition-colors border-b-2 -mb-px ${
              i === 0
                ? 'border-[var(--accent)] text-[var(--text-primary)]'
                : 'border-transparent text-[var(--text-secondary)] hover:text-[var(--text-primary)]'
            }`}
          >
            {tab}
          </button>
        ))}
      </div>

      <div className="space-y-4">
        {MOCK_POSTS.map((post) => (
          <div key={post.id} className="rounded-xl border border-[var(--border-medium)] bg-[var(--bg-card)] overflow-hidden">
            <div className="flex items-center justify-between px-5 py-3 border-b border-[var(--border-light)] bg-[var(--bg-secondary)]">
              <div className="flex items-center gap-2 text-sm">
                <span className="font-semibold text-[var(--text-primary)]">{post.platform}</span>
                <span className="text-[var(--text-tertiary)]">·</span>
                <span className="flex items-center gap-1 text-[var(--text-tertiary)]">
                  <Clock size={12} />
                  {post.scheduledFor}
                </span>
              </div>
              <span className="text-xs text-[var(--text-tertiary)]">from: {post.source}</span>
            </div>
            <div className="px-5 py-4">
              <p className="text-sm text-[var(--text-primary)] leading-relaxed">{post.body}</p>
            </div>
            <div className="flex items-center gap-2 px-5 py-3 border-t border-[var(--border-light)]">
              <button className="btn btn-primary btn-sm flex items-center gap-1.5">
                <CheckCircle2 size={14} />
                Approve
              </button>
              <button className="btn btn-secondary btn-sm flex items-center gap-1.5">
                <Edit3 size={14} />
                Edit
              </button>
              <button className="ml-auto btn btn-sm text-[var(--text-tertiary)] hover:text-[var(--error)] hover:bg-[var(--error)]/10 flex items-center gap-1.5">
                <X size={14} />
                Skip
              </button>
            </div>
          </div>
        ))}

        <div className="text-center py-8 text-[var(--text-tertiary)] text-sm border border-dashed border-[var(--border-light)] rounded-xl">
          <Share2 size={24} className="mx-auto mb-3 opacity-30" />
          <p className="font-medium mb-1">Posts are generated after processing uploads</p>
          <p>Connect your X account in Settings to enable auto-posting.</p>
        </div>
      </div>
    </div>
  )
}
