/**
 * B-roll detail — auto tags, operator notes, usage history.
 */
export const runtime = 'edge'

export default function BRollDetailPage({ params }: { params: { id: string } }) {
  return (
    <main>
      <a href="/timeline" className="detail-back">← Timeline</a>
      <div className="detail-stage">
        <section style={{ paddingTop: 24 }}>
          <div className="kicker">B-roll asset · {params.id.slice(0, 8)}</div>
          <h1 style={{ fontWeight: 500, fontSize: 26, letterSpacing: '-0.5px', margin: '8px 0 16px' }}>Visual fragment</h1>
        </section>

        <div className="section">
          <div style={{ aspectRatio: '16/9', background: 'linear-gradient(135deg, var(--bg-2), var(--bg-1))', border: '1px solid var(--line)', borderRadius: 12 }} />
        </div>

        <div className="section">
          <div className="section-label">Auto tags</div>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6 }}>
            {['interior', 'window light', 'evening', 'amber', 'desk', 'static'].map(t => (
              <span key={t} style={{
                padding: '6px 12px',
                border: '1px solid var(--line-2)',
                borderRadius: 100,
                fontFamily: 'JetBrains Mono, monospace',
                fontSize: 9,
                letterSpacing: 1.5,
                textTransform: 'uppercase',
                color: 'var(--fg-3)',
              }}>{t}</span>
            ))}
          </div>
          <p style={{ marginTop: 12, fontSize: 12, color: 'var(--fg-4)' }}>Tags auto-generated by the vision-tag-broll Workflow (staged).</p>
        </div>

        <div className="section">
          <div className="section-label">Usage</div>
          <p style={{ color: 'var(--fg-2)', fontSize: 13 }}>Not used in any production yet.</p>
        </div>
      </div>
    </main>
  )
}
